version: "3.8"

services:
  nginx:
    build:
      context: ./client/
      dockerfile: Dockerfile.prod
    image: gabelluardo/solidarity-purchasing-group:release1-client
    restart: always
    # production mode is on port 80
    ports:
      - 80:80
    depends_on:
      - server
    environment:
      NODE_ENV: production

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile.prod
    image: gabelluardo/solidarity-purchasing-group:release1-server
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3001
